name: CI
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'example/**'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      debug-enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: true
        default: false
      debug-os:
        description: 'Operating System'
        required: true
        default: 'Ubuntu LTS (amd64)'
        type: choice
        options:
          - 'Ubuntu LTS (amd64)'
          - 'Ubuntu LTS (arm64)'
          - 'macOS Latest (arm64)'
          - 'macOS 13 (amd64)'
          - 'Windows Latest (amd64)'
          - 'Windows Latest (arm64)'

jobs:
  common-tests:
    name: Test
    uses: ./.github/workflows/common-tests.yaml
    with:
      debug-enabled: ${{ inputs.debug-enabled || false }}
      debug-os: >-
        ${{
          inputs.debug-os == 'Ubuntu LTS (amd64)' && 'ubuntu-latest' ||
          inputs.debug-os == 'Ubuntu LTS (arm64)' && 'ubuntu-24.04-arm' ||
          inputs.debug-os == 'macOS Latest (arm64)' && 'macos-latest' ||
          inputs.debug-os == 'macOS 13 (amd64)' && 'macos-13' ||
          inputs.debug-os == 'Windows Latest (amd64)' && 'windows-latest' ||
          inputs.debug-os == 'Windows Latest (arm64)' && 'windows-11-arm' || 
          ''
        }}
    
