name: Test
on:
  workflow_call:
    inputs:
      debug-enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      debug-os:
        description: 'Operating System to debug'
        required: true
        default: ''
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  debug-check:
    name: Debug Mode Check
    runs-on: ubuntu-latest
    outputs:
      enabled: ${{ !inputs.debug-enabled }}
      os: ${{ inputs.debug-os || '' }}
    steps:
      - name: Check Debug Mode
        run: |
          if [ "${{ inputs.debug-enabled }}" == "true" ]; then
            echo "Debug mode enabled - will run only on ${{ inputs.debug-os }}"
          else
            echo "Normal mode"
          fi

  test:
    name: Test ${{ matrix.name }}
    needs: [ debug-check ]
    # Only run this job if we're in normal mode OR this is the debug OS
    if: (!needs.debug-check.outputs.enabled) || (needs.debug-check.outputs.enabled == 'true' && matrix.os == needs.debug-check.outputs.os)
    strategy:
      matrix:
        include:
          - name: Linux (amd64)
            os: ubuntu-latest
          - name: Linux (arm64)
            os: ubuntu-24.04-arm
          - name: MacOS (amd64)
            os: macos-13
          - name: MacOS (arm64)
            os: macos-latest
          - name: Windows (amd64)
            os: windows-latest
            continue-on-error: true # TODO: Windows is not well supported
          - name: Windows (arm64)
            os: windows-11-arm
            continue-on-error: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.continue-on-error || false }}
    steps:
      - uses: actions/checkout@v4

      - name: OS Info
        uses: ./.github/actions/os-info

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Prepare dependencies
        run: |
          go install github.com/go-delve/delve/cmd/dlv@latest
          go mod download

      - name: Setup debug session
        if: needs.debug-check.outputs.enabled == 'true'
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Test
        if: needs.debug-check.outputs.enabled == 'false'
        id: run-tests
        run: |
          go test ./...

  lint:
    name: Lint code
    needs: [ debug-check ]
    # Only run this job if we're in normal mode OR this is the debug OS
    if: needs.debug-check.outputs.enabled == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Test
        id: run-tests
        run: make lint
