name: Test
on:
  workflow_call:
    inputs:
      os:
        description: 'OS to run'
        type: string
        required: true
        default: ''

jobs:
  debug:
    name: Debug
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: OS Info
        uses: ./.github/actions/os-info

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Prepare dependencies
        run: |
          go install github.com/go-delve/delve/cmd/dlv@latest
          go mod download

      - name: Setup debug session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Fail in debug mode
        run: exit 1