name: Linux Docker Sidecar

on:
  workflow_dispatch:
    inputs:
      sidecar-id:
        required: true
        type: string
        description: 'Unique ID for this sidecar instance'
      timeout:
        required: false
        type: string
        default: '3600'
        description: 'Maximum time in seconds to keep sidecar alive'

jobs:
  run-sidecar:
    name: Run Linux Docker Sidecar
    uses: lexbritvin/docker-sidecar-action/.github/workflows/linux-sidecar.yaml@main
    with:
      sidecar-id: ${{ inputs.sidecar-id }}
      timeout: ${{ inputs.timeout }}
    secrets:
      GH_TOKEN: ${{ github.token }}